export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


export const FORGETPASSWORD = "FORGETPASSWORD";
export const FORGETPASSWORD_FAIL = "FORGETPASSWORD_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_QUEUE_SUCCESS = "ADD_QUEUE_SUCCESS";
export const ADD_QUEUE_FAIL = "ADD_QUEUE_FAIL";
export const CANCEL_QUEUE_SUCCESS = "CANCEL_QUEUE_SUCCESS";
export const LIST_USER_QUEUE = "LIST_USER_QUEUE";
export const VIEW_QUEUE = "VIEW_QUEUE";

export const BUSINESS_DETAIL = "BUSINESS_DETAIL"

export const FETCH_QUEUE_UPDATETING = "FETCH_QUEUE_UPDATETING"
export const FETCH_QUEUE_UPDATETING_SUCCESS = "FETCH_QUEUE_UPDATETING_SUCCESS"

